# -*- coding: utf-8 -*-
"""扩充版词根词缀数据（常用优先，星级3=最高频）。

格式：
PREFIXES: (名称, 来源, 含义, 代表词, 辨析, 星级)
SUFFIXES: (名称, 来源, 含义, 代表词, 辨析, 星级)
ROOTS:    (名称, 来源, 含义, 代表词, 星级)
"""

PREFIXES = [
    # ============ ★★★ 最高频 ============
    ("un-", "日耳曼", "不；反向", "unhappy, undo, unfair", "最通用否定，表状态", 3),
    ("re-", "拉丁", "再；回", "return, review, recycle", "转回去/再来一遍", 3),
    ("in-/il-/im-/ir-", "拉丁", "不；向内", "illegal, input, impossible", "辅音同化", 3),
    ("dis-", "拉丁", "否定；分离", "disagree, disconnect", "主动反向动作", 3),
    ("non-", "拉丁", "非；不", "nonstop, nonfiction", "客观分类'非'", 3),
    ("mis-", "日耳曼", "错；坏", "mistake, mislead", "做错、方式不对", 3),
    ("pre-", "拉丁", "预先", "prepare, predict", "时间上提前", 3),
    ("post-", "拉丁", "之后", "postpone, postwar", "时间上之后", 3),
    ("ex-/e-/ef-", "拉丁", "向外", "exit, export, effect", "向外离开；也表前任", 3),
    ("sub-/suc-/suf-", "拉丁", "在下；次", "subway, support", "下面/次要", 3),
    ("super-/sur-", "拉丁", "在上；超", "supermarket, survive", "高度程度超", 3),
    ("trans-/tra-", "拉丁", "横跨", "transport, translate", "从一边到另一边", 3),
    ("inter-/intel-", "拉丁", "之间", "international, interview", "在…之间", 3),
    ("com-/con-/co-/col-/cor-", "拉丁", "一起", "combine, cooperate", "辅音同化", 3),
    ("pro-/pr-", "拉丁", "向前；支持", "progress, promote", "方向/立场", 3),
    ("per-/pel-", "拉丁", "贯穿；彻底", "perfect, persist", "从头到尾完整", 3),
    ("de-/di-", "拉丁", "向下；反转", "decrease, decode", "往下/反过来", 3),
    ("over-", "日耳曼", "过度；在上", "overwork, overdue", "超出正常量", 3),
    ("under-", "日耳曼", "在下；不足", "underground, underage", "下方/未达标", 3),
    ("fore-", "日耳曼", "在前；预", "forecast, forehead", "位置在前", 3),
    ("out-", "日耳曼", "向外；超", "output, outstanding", "向外/超过", 3),
    ("un-", "日耳曼", "（动词）相反动作", "unlock, untie", "打开/解开", 3),
    # ============ ★★ 高频 ============
    ("anti-/ant-", "希腊", "对抗", "antibiotic, antiwar", "反对对抗", 2),
    ("semi-/demi-", "拉丁", "半", "semicircle, semifinal", "一半", 2),
    ("bi-/bin-", "拉丁", "二", "bicycle, bilingual", "两个", 2),
    ("multi-/mult-", "拉丁", "多", "multimedia, multiply", "许多", 2),
    ("mono-/mon-", "希腊", "单一", "monologue, monopoly", "一个", 2),
    ("circum-/circu-", "拉丁", "环绕", "circumference, circumstance", "围绕一圈", 2),
    ("intro-/intra-", "拉丁", "向内/内部", "introduce, intravenous", "向内/内部", 2),
    ("extra-/extro-", "拉丁", "超出；外", "extraordinary, extrovert", "超出正常", 2),
    ("contra-/counter-", "拉丁", "反对；相对", "contradict, counterattack", "对立相对", 2),
    ("syn-/sym-/syl-/sys-", "希腊", "一起；同", "symphony, system", "合成一体", 2),
    ("tele-/tel-", "希腊", "远", "telephone, television", "距离远", 2),
    ("auto-/aut-", "希腊", "自己", "automatic, autograph", "自身", 2),
    ("micro-/micr-", "希腊", "微小", "microscope, microbe", "小", 2),
    ("en-/em-", "日耳曼/希腊", "使；进入", "enable, empower", "使成为", 2),
    ("ante-/anti-", "拉丁", "在前", "antenatal, antebellum", "时间/位置在前", 2),
    ("be-", "日耳曼", "使；围绕", "become, belittle", "使成为", 2),
    ("ad-/ac-/af-/ag-/al-/an-/ap-/ar-/as-/at-", "拉丁", "朝向", "advance, adapt", "朝…方向，同化", 2),
    ("ab-/abs-", "拉丁", "离开；远离", "absent, abuse", "离开", 2),
    ("retro-/retr-", "拉丁", "向后", "retrospective, retroactive", "往回", 2),
    ("equi-/equ-", "拉丁", "相等", "equal, equation", "相等", 2),
    ("uni-/un-", "拉丁", "一", "unique, union", "一个", 2),
    ("tri-/tri-", "拉丁/希腊", "三", "triangle, triple", "三个", 2),
    ("quadr-/quart-", "拉丁", "四", "quadrant, quarter", "四个", 1),
    ("penta-/pent-", "希腊", "五", "pentagon, pentagram", "五个", 1),
    ("hex-/sext-", "希腊/拉丁", "六", "hexagon, sextant", "六个", 1),
    ("sept-/hept-", "拉丁/希腊", "七", "September, heptagon", "七个", 1),
    ("oct-/octa-", "希腊", "八", "octopus, October", "八个", 1),
    ("nov-/ennea-", "拉丁/希腊", "九", "November, enneagram", "九个", 1),
    ("dec-/deci-", "拉丁", "十", "December, decimal", "十个", 1),
    ("cent-/centi-", "拉丁", "百", "century, centimeter", "百", 1),
    ("kilo-/milli-", "希腊/拉丁", "千", "kilogram, millimeter", "千", 1),
    ("hemi-/semi-", "希腊/拉丁", "半", "hemisphere, semicircle", "半", 2),
    ("pan-/panto-", "希腊", "全部", "pandemic, panorama", "全体", 2),
    ("omni-", "拉丁", "全；都", "omnipotent, omniscient", "全部都能", 2),
    ("poly-/pol-", "希腊", "多", "polytechnic, polyglot", "多个", 2),
    ("hyper-/hyp-", "希腊", "超过；过度", "hyperactive, hypertext", "医学科学多用", 2),
    ("hypo-/hyp-", "希腊", "低下", "hypothesis, hypothermia", "低于正常", 2),
    ("para-/par-", "希腊", "旁边；异常", "parallel, paragraph", "在旁/类似", 2),
    ("mega-/megal-", "希腊", "巨大", "megaphone, megastar", "巨大", 2),
    ("macro-/macr-", "希腊", "大；长", "macroeconomics, macro", "大规模", 2),
    ("ultra-", "拉丁", "极端；超出", "ultrasonic, ultraviolet", "极端", 2),
    ("post-/postero-", "拉丁", "后", "posterior, postpone", "后面", 2),
    ("pre-/prae-", "拉丁", "前", "previous, preview", "先前", 2),
    ("pro-/proto-", "希腊", "最初；原始", "prototype, proton", "原始第一", 2),
    ("eu-", "希腊", "好；优", "euphemism, eulogy", "好美好", 2),
    ("mal-/male-", "拉丁", "坏；恶", "malfunction, malevolent", "坏的", 2),
    ("bene-/ben-", "拉丁", "好；善", "benefit, benevolent", "好的", 2),
    ("a-/an-", "希腊", "不；无", "amoral, anonymous", "否定（学术词）", 2),
    ("de-", "拉丁", "（动词）去除", "decode, debug", "去掉", 2),
    # ============ ★ 常用 ============
    ("ab-/a-", "拉丁", "离开；从", "abnormal, abduct", "离开/从中", 1),
    ("amb-/ambi-", "拉丁", "两；周围", "ambidextrous, ambiguous", "两/双", 1),
    ("amphi-/amph-", "希腊", "两；周围", "amphibian, amphitheater", "两栖", 1),
    ("ana-/an-", "希腊", "向上；再", "analysis, anagram", "分析", 1),
    ("apo-/ap-", "希腊", "离开；远离", "apology, apostrophe", "远离", 1),
    ("arch-/archeo-", "希腊", "最初；首领", "archaeology, architect", "古老/首领", 1),
    ("cata-/cat-", "希腊", "向下；彻底", "catalog, catastrophe", "向下/灾难", 1),
    ("cis-", "拉丁", "在…这边", "cisgender, cisalpine", "同侧", 1),
    ("di-/dia-", "希腊", "通过；穿过", "diameter, dialogue", "透过", 2),
    ("dif-/dis-", "拉丁", "分开", "differ, different", "分开", 2),
    ("dys-", "希腊", "困难；异常", "dyslexia, dysfunction", "障碍", 1),
    ("eco-", "希腊", "生态；环境", "ecology, economy", "环境", 2),
    ("endo-/ent-", "希腊", "在内", "endoscope, internal", "内部", 1),
    ("epi-/eph-", "希腊", "在…之上", "epidemic, epilogue", "在上/周围", 1),
    ("eso-", "希腊", "向内", "esoteric", "内隐", 1),
    ("exo-/ecto-", "希腊", "在外", "exotic, exoskeleton", "外部", 1),
    ("hetero-/heter-", "希腊", "异；不同", "heterosexual, heterogeneous", "不同", 1),
    ("homo-/hom-", "希腊", "同；相同", "homogeneous, homonym", "相同", 1),
    ("infra-/infr-", "拉丁", "在…之下", "infrastructure, infrared", "下部", 1),
    ("iso-", "希腊", "相等", "isometric, isotope", "等", 1),
    ("juxta-", "拉丁", "紧邻", "juxtapose", "并列", 1),
    ("meta-/met-", "希腊", "变化；之后", "metamorphosis, metaphor", "变形/超越", 1),
    ("ne-/neo-", "希腊", "新", "neon, neoclassical", "新", 1),
    ("ob-/oc-/of-/op-", "拉丁", "朝向；逆", "obey, object", "朝向/阻碍", 1),
    ("paleo-/pal-", "希腊", "古", "paleontology, paleolithic", "古老", 1),
    ("pseudo-/pseud-", "希腊", "假；伪", "pseudonym, pseudo", "假的", 1),
    ("quasi-", "拉丁", "类似；准", "quasi-static, quasi-official", "类似", 1),
    ("semi-", "拉丁", "一半", "semicolon, semitone", "半", 2),
    ("step-", "日耳曼", "继（亲）", "stepmother, stepson", "再婚家庭", 1),
    ("ultra-", "拉丁", "极端", "ultraviolet", "极端", 1),
    ("vice-", "拉丁", "副；代替", "vice-president, vice versa", "副职", 2),
    ("with-", "日耳曼", "相反；离开", "withdraw, withstand", "收回/抵抗", 1),
    ("mid-", "日耳曼", "中间", "midnight, midpoint", "中部", 2),
    ("up-", "日耳曼", "向上", "update, upgrade", "向上", 2),
    ("down-", "日耳曼", "向下", "download, downtown", "向下", 1),
    ("un-", "日耳曼", "不（形容词）", "unable, unknown", "不", 3),
    ("in-", "拉丁", "在…内", "inside, income", "在内", 3),
    ("by-/bye-", "日耳曼", "次要；旁边", "bystander, byproduct", "旁边/副", 1),
    ("fore-/fur-", "日耳曼", "前面", "foreground, former", "前面", 2),
    ("out-", "日耳曼", "超过", "outrun, outdo", "胜过", 2),
    ("over-", "日耳曼", "覆盖", "overlook, oversee", "俯视", 2),
    ("through-", "日耳曼", "穿过", "throughout, thorough", "全程", 1),
    ("for-", "日耳曼", "禁止；离", "forbid, forget", "不去", 1),
    ("gain-", "日耳曼", "相反", "gainsay", "否认", 1),
    ("a-/an-", "希腊", "（学术）非", "atheist, asexual", "无", 2),
]

SUFFIXES = [
    # ============ 名词后缀 ============
    ("-tion/-sion/-ion", "拉丁", "名词(动作/结果)", "information, decision", "动词变名词最常用", 3),
    ("-ment", "拉丁", "名词(结果/产物)", "development, agreement", "加动词表结果", 3),
    ("-ness", "日耳曼", "名词(状态/感觉)", "happiness, kindness", "加形容词最万能", 3),
    ("-ity/-ty", "拉丁", "名词(性质/属性)", "ability, reality", "加形容词客观属性", 3),
    ("-er/-or/-ar", "日耳曼/拉丁", "…的人/物", "teacher, actor", "施动者", 3),
    ("-ist", "希腊", "…的人(专业)", "artist, scientist", "专业人员/主义", 3),
    ("-ance/-ence/-ancy/-ency", "拉丁", "名词(状态)", "importance, patience", "配 -ant/-ent", 2),
    ("-ship", "日耳曼", "名词(身份/关系)", "friendship, leadership", "人际关系", 2),
    ("-hood", "日耳曼", "名词(阶段/群体)", "childhood, neighborhood", "人生阶段", 2),
    ("-dom", "日耳曼", "名词(领域/状态)", "kingdom, freedom", "统治领域", 2),
    ("-age", "拉丁/法语", "名词(行为/总量)", "usage, luggage", "行为或集合量", 2),
    ("-ant/-ent/-ent", "拉丁", "…的人(分词)", "assistant, student", "正在做…的人", 2),
    ("-ee", "法语", "被…的人", "employee, trainee", "动作接受者", 2),
    ("-ism", "希腊", "主义；行为", "realism, tourism", "思想体系", 2),
    ("-ology/-logy", "希腊", "学科；学问", "biology, psychology", "…学", 2),
    ("-graphy", "希腊", "记录；写法", "biography, photography", "…记录", 1),
    ("-meter/-metry", "希腊", "测量仪器", "thermometer, geometry", "…计", 1),
    ("-scope", "希腊", "观察仪器", "microscope, telescope", "…镜", 1),
    ("-phone", "希腊", "声音；电话", "telephone, microphone", "声音设备", 1),
    ("-cide", "拉丁", "杀；灭", "suicide, pesticide", "杀死…", 1),
    ("-phobia", "希腊", "恐惧症", "claustrophobia", "恐惧", 1),
    ("-phile", "希腊", "爱好…者", "bibliophile", "喜爱", 1),
    ("-ess/-ette", "法语", "女性/小", "actress, cigarette", "阴性/小号", 1),
    ("-gram/-graph", "希腊", "写出的东西", "diagram, photograph", "图/记录", 1),
    ("-sphere", "希腊", "球；范围", "atmosphere, hemisphere", "球体", 1),
    ("-ation/-ition", "拉丁", "名词(过程)", "creation, position", "行为过程", 2),
    ("-al/-ial", "拉丁", "名词/形容词", "arrival, natural", "…的；名词", 3),
    ("-ance/-ence", "拉丁", "名词", "performance, difference", "状态", 2),
    ("-ary/-ery/-ory", "拉丁", "名词/形容词", "library, factory, history", "场所/性质", 2),
    ("-tude/-itude", "拉丁", "名词(程度)", "attitude, magnitude", "状态程度", 1),
    ("-ness/-ness", "日耳曼", "名词", "darkness, weakness", "状态", 3),
    ("-acy/-cy", "拉丁", "名词(性质)", "democracy, accuracy", "状态", 1),
    ("-ure/-ture", "拉丁", "名词(行为)", "culture, pressure", "行为结果", 2),
    ("-ice/-ise", "法语", "名词", "justice, practice", "性质", 1),
    ("-ian/-an", "拉丁", "…的人/国人", "musician, American", "从事者", 2),
    ("-eer/-ier", "法语", "…的人", "engineer, pioneer", "从事者", 1),
    ("-let/-ling", "日耳曼", "小", "booklet, duckling", "小号", 1),
    ("-ment", "拉丁", "名词", "payment, government", "行为结果", 3),
    ("-ism/-ism", "希腊", "主义", "socialism, capitalism", "思想", 2),
    ("-ics/-tics", "希腊", "学科", "physics, politics", "…学", 2),
    # ============ 形容词后缀 ============
    ("-ful", "日耳曼", "充满…的", "careful, beautiful", "…满满", 3),
    ("-less", "日耳曼", "无…的", "careless, helpless", "…没有", 3),
    ("-able/-ible", "拉丁", "可…的", "comfortable, reliable", "能被…的", 3),
    ("-ous/-ious/-uous", "拉丁", "充满…的", "dangerous, famous", "带来/具有", 3),
    ("-ive/-ative/-itive", "拉丁", "倾向于…的", "active, creative", "爱做/能做", 3),
    ("-ic/-ical", "希腊/拉丁", "…的(学术)", "economic, historic", "偏学术", 2),
    ("-ish", "日耳曼", "略带…的", "childish, British", "有点…", 2),
    ("-y/-ly", "日耳曼", "多…的", "rainy, happy", "口语化", 2),
    ("-like", "日耳曼", "像…的", "childlike, lifelike", "相似", 2),
    ("-ward", "日耳曼", "朝…方向", "forward, backward", "方向", 2),
    ("-wise", "日耳曼", "以…方式", "clockwise, otherwise", "方式", 1),
    ("-proof", "日耳曼", "防…的", "waterproof, fireproof", "防…", 1),
    ("-al/-ar", "拉丁", "…的", "natural, solar", "相关", 3),
    ("-an/-ian", "拉丁", "…的；…人", "urban, American", "归属", 2),
    ("-ary", "拉丁", "…的", "necessary, ordinary", "相关", 2),
    ("-ate", "拉丁", "…的；有…的", "fortunate, accurate", "有…特征", 2),
    ("-en/-ern", "日耳曼", "由…制成", "wooden, golden", "材质", 2),
    ("-esque", "法语", "…风格", "picturesque, grotesque", "像…", 1),
    ("-fold", "日耳曼", "…倍", "twofold, manifold", "倍数", 1),
    ("-id", "拉丁", "有…性质的", "liquid, valid", "性质", 1),
    ("-ile/-il", "拉丁", "可…的；…的", "fragile, mobile", "易…", 2),
    ("-ine/-in", "拉丁", "…的", "divine, feminine", "属性", 1),
    ("-less", "日耳曼", "不…的", "endless, fearless", "无", 3),
    ("-most", "日耳曼", "最…的", "foremost, utmost", "最", 1),
    ("-some", "日耳曼", "…的", "handsome, tiresome", "有…性质", 1),
    ("-tive", "拉丁", "…的", "native, positive", "倾向", 2),
    ("-ual", "拉丁", "…的", "actual, gradual", "相关", 2),
    # ============ 动词后缀 ============
    ("-ize/-ise", "希腊", "使…化", "realize, organize", "使变成", 3),
    ("-ify/-fy", "拉丁", "使…", "clarify, magnify", "使成为", 2),
    ("-ate", "拉丁", "使…；做…", "activate, communicate", "动词化", 2),
    ("-en", "日耳曼", "使…", "strengthen, darken", "使变", 2),
    ("-ish", "日耳曼", "使…（动词）", "finish, punish", "动词化", 1),
    ("-er", "日耳曼", "反复动作", "stutter, wander", "反复", 1),
    # ============ 副词后缀 ============
    ("-ly", "日耳曼", "…地", "quickly, happily", "形容词+ly", 3),
    ("-ward(s)", "日耳曼", "向…", "backward, homewards", "方向", 2),
    ("-wise", "日耳曼", "以…方式", "clockwise, likewise", "方式", 1),
    ("-ways/-way", "日耳曼", "朝…方向", "always, sideways", "方向", 1),
]

ROOTS = [
    # ============ 感官与认知 ============
    ("spect/spic", "拉丁", "看", "expect 期待, respect 尊重", 3),
    ("vis/vid", "拉丁", "看", "visible 可见, vision 视力", 3),
    ("dict/dic", "拉丁", "说", "predict 预测, dictionary 词典", 3),
    ("voc/vok", "拉丁", "喊；声音", "vocal 嗓音, provoke 激怒", 3),
    ("scrib/script", "拉丁", "写", "describe 描述, subscribe 订阅", 3),
    ("graph/gram", "希腊", "写；画", "photograph 照片, biography 传记", 3),
    ("log/logue/ology", "希腊", "话；道理；学", "logic 逻辑, dialogue 对话", 3),
    ("phon/phon", "希腊", "声音", "phone 电话, symphony 交响乐", 3),
    ("son/son", "拉丁", "声音", "resonate 共鸣, person 人", 2),
    ("aud/audit", "拉丁", "听", "audience 观众, audio 音频", 3),
    ("scope/scop", "希腊", "看；检查", "telescope 望远镜, scope 范围", 2),
    ("sens/sent", "拉丁", "感觉", "sense 感觉, consent 同意", 3),
    ("path/path", "希腊", "感受；病", "sympathy 同情, pathology 病理", 3),
    ("psych/psyche", "希腊", "心灵", "psychology 心理学, psychic", 2),
    ("sci/scient", "拉丁", "知道", "science 科学, conscious", 3),
    ("cred/credo", "拉丁", "相信", "credit 信用, incredible", 3),
    ("fid/fide", "拉丁", "信任", "confident 自信, fidelity", 2),
    ("soph/soph", "希腊", "智慧", "philosophy 哲学, sophisticated", 2),
    ("anim/anim", "拉丁", "生命；心灵", "animal 动物, unanimous", 2),
    ("vol/volunt", "拉丁", "意愿", "volunteer 志愿者, voluntary", 2),
    ("clar/clar", "拉丁", "清晰", "clarify 澄清, declare 宣布", 2),
    ("cogn/cognit", "拉丁", "认识", "recognize 认识, cognition 认知", 2),
    ("gnos/gnost", "希腊", "认识", "diagnosis 诊断, prognosis", 1),
    ("mem/memor", "拉丁", "记忆", "memory 记忆, remember", 3),
    ("ment/ment", "拉丁", "心智", "mental 精神, mention", 2),
    ("neur/neuro", "希腊", "神经", "neuron 神经元, nervous", 1),
    ("psych", "希腊", "心灵", "psychology 心理学", 2),
    # ============ 做与造 ============
    ("fac/fact/fect/fic", "拉丁", "做", "factory 工厂, perfect 完美", 3),
    ("ag/act/ag", "拉丁", "做；驱动", "action 行动, agent 代理", 3),
    ("struct/stru", "拉丁", "建造", "structure 结构, construct", 3),
    ("form/form", "拉丁", "形状", "inform 通知, transform", 3),
    ("morph/morph", "希腊", "形态", "metamorphosis 蜕变", 1),
    ("pos/pon/posit", "拉丁", "放", "position 位置, compose", 3),
    ("loc/locat", "拉丁", "地方", "local 当地, locate 定位", 3),
    ("techn/tech", "希腊", "技艺", "technology 科技, technique", 2),
    ("art/arti", "拉丁", "技艺", "artist 艺术家, artificial", 3),
    ("labor/lab", "拉丁", "工作", "laboratory 实验室, collaborate", 3),
    ("oper/opera", "拉丁", "工作；操作", "operate 操作, cooperate", 2),
    ("erg/urg", "希腊", "工作；力", "energy 能量, ergonomics", 1),
    ("plasm/plast", "希腊", "塑造", "plasma, plastic 塑料", 1),
    ("fab/fabric", "拉丁", "制造；织物", "fabric 布料, fabricate 制造", 1),
    ("doct/doc", "拉丁", "教", "doctor 医生, doctrine 教义", 2),
    ("educ/edu", "拉丁", "教育", "educate 教育, education", 3),
    # ============ 拿与持 ============
    ("cap/capt/cept/ceive", "拉丁", "拿；抓", "capture 捕获, receive", 3),
    ("ten/tin/tain", "拉丁", "握住；保持", "contain 包含, retain", 3),
    ("tact/tang/tag", "拉丁", "触摸", "contact 接触, intact", 3),
    ("sum/sumpt", "拉丁", "拿起；取用", "assume 承担, consume 消费", 2),
    ("prehend/prehens", "拉丁", "抓住；理解", "comprehend 理解, apprehend", 1),
    ("rap/rapt/rav", "拉丁", "抢夺", "rapid 快速, rapture 狂喜", 1),
    ("em/empt", "拉丁", "买；取", "redeem 赎回, example 例子", 1),
    ("hab/hibit", "拉丁", "拥有；持有", "habit 习惯, exhibit 展出", 2),
    ("heir/herit", "拉丁", "继承", "heir 继承人, inherit 继承", 1),
    ("cept/ceive", "拉丁", "拿（变体）", "receive, perceive", 3),
    # ============ 运动 ============
    ("ceed/cess/cede", "拉丁", "走", "proceed 进行, success 成功", 3),
    ("grad/gress", "拉丁", "步；走", "grade 等级, progress 进步", 3),
    ("vad/vas", "拉丁", "走", "invade 侵略, evade 逃避", 2),
    ("curr/curs/cour", "拉丁", "跑；流", "current 当前, currency 货币", 3),
    ("mov/mot/mob", "拉丁", "移动", "motion 运动, mobile 移动", 3),
    ("flu/flux/fluv", "拉丁", "流动", "fluent 流利, influence 影响", 3),
    ("migr/migr", "拉丁", "迁移", "migrate 迁移, immigrant", 2),
    ("volv/volu/volut", "拉丁", "滚；转", "evolve 演化, revolve", 2),
    ("mut/mut", "拉丁", "变化", "mutate 突变, mutual 相互", 2),
    ("ven/vent", "拉丁", "来", "event 事件, prevent 阻止", 3),
    ("fer/fert", "拉丁", "携带", "transfer 转移, refer 提及", 3),
    ("port/port", "拉丁", "搬运", "transport 运输, support", 3),
    ("mit/miss/mis", "拉丁", "送；放出", "admit 承认, mission 任务", 3),
    ("ject/jet", "拉丁", "投；掷", "inject 注射, reject 拒绝", 3),
    ("ambul/ambul", "拉丁", "行走", "ambulance 救护车", 1),
    ("it/it/itis", "拉丁", "走", "exit 出口, transit 过境", 2),
    ("nav/navi", "拉丁", "船", "navy 海军, navigate 导航", 2),
    ("veh/vect", "拉丁", "运载", "vehicle 车辆, vector 矢量", 1),
    ("ped/ped", "拉丁", "脚；行", "pedal 踏板, pedestrian 行人", 3),
    ("plaud/plod", "拉丁", "拍；走", "applaud 鼓掌, explode 爆炸", 1),
    ("surg/surge", "拉丁", "上升；涌", "surge 涌, surgeon 外科医生", 1),
    # ============ 破坏与施力 ============
    ("rupt/rupt", "拉丁", "打破", "erupt 喷发, interrupt 打断", 3),
    ("frag/fract", "拉丁", "打碎", "fragile 易碎, fracture 骨折", 3),
    ("cid/cis", "拉丁", "切；杀", "decide 决定, suicide 自杀", 3),
    ("press/press", "拉丁", "压", "express 表达, pressure 压力", 3),
    ("tract/trah", "拉丁", "拉；拖", "attract 吸引, extract 提取", 3),
    ("clin/clin", "拉丁", "倾斜", "decline 下降, incline 倾向", 2),
    ("tort/tors", "拉丁", "扭曲", "torture 折磨, distort 扭曲", 1),
    ("sect/sec", "拉丁", "切割", "section 部分, insect 昆虫", 2),
    ("flect/flex", "拉丁", "弯曲", "reflect 反射, flexible 灵活", 2),
    ("punct/pung", "拉丁", "刺；点", "punctual 准时, puncture 刺破", 2),
    ("strict/strain", "拉丁", "拉紧", "strict 严格, constrain 约束", 2),
    ("string/strict", "拉丁", "捆扎；拉紧", "string 绳子, restrict 限制", 2),
    ("cut/cuss", "拉丁", "打击", "cut 切, percussion 打击乐", 1),
    ("fend/fens", "拉丁", "抵挡", "defend 防御, offensive 进攻", 2),
    ("lac/lect", "拉丁", "拉；诱", "elicit 引出, reluctance 勉强", 1),
    ("puls/pel", "拉丁", "推", "compel 强迫, impulse 冲动", 2),
    ("trud/trus", "拉丁", "推；插入", "intrude 闯入, obtrusive", 1),
    ("vinc/vict", "拉丁", "征服", "victory 胜利, convince 说服", 2),
    ("cid/cis", "拉丁", "砍", "incision 切口, scissors 剪刀", 1),
    # ============ 生命与自然 ============
    ("bio/bio", "希腊", "生命", "biology 生物学, biography", 3),
    ("vit/viv/vivi", "拉丁", "生命；活", "vivid 生动, survive 幸存", 3),
    ("nat/nasc", "拉丁", "出生", "nation 国家, native 本土", 3),
    ("gen/gener", "拉丁", "出生；种类", "generate 产生, generation", 3),
    ("mort/mort", "拉丁", "死亡", "mortal 凡人, immortal 不朽", 2),
    ("spir/spirit", "拉丁", "呼吸", "inspire 激励, spirit 精神", 3),
    ("hydr/hydr", "希腊", "水", "hydrate 水合, hydrogen 氢", 3),
    ("aqua/aqu", "拉丁", "水", "aquarium 水族馆, aquatic", 2),
    ("mar/mari", "拉丁", "海", "marine 海洋, submarine 潜艇", 2),
    ("therm/thermo", "希腊", "热", "thermal 热力, thermometer", 3),
    ("luc/lux/lumin", "拉丁", "光", "lucid 清晰, illuminate 照亮", 2),
    ("astr/aster", "希腊", "星", "astronaut 宇航员, disaster", 2),
    ("terr/terra", "拉丁", "土地", "territory 领土, terrain 地形", 2),
    ("cosm/cosm", "希腊", "宇宙；秩序", "cosmos 宇宙, cosmopolitan", 1),
    ("cycl/cycl", "希腊", "圆；环", "cycle 周期, bicycle 自行车", 3),
    ("stell/stell", "拉丁", "星", "stellar 恒星的, constellation", 1),
    ("flor/flor", "拉丁", "花", "flourish 繁荣, flower 花", 1),
    ("sol/solar", "拉丁", "太阳", "solar 太阳的, solarium 日光室", 2),
    ("lun/lunar", "拉丁", "月亮", "lunar 月亮的, lunatic 疯狂的", 1),
    ("geo/geo", "希腊", "地球；土地", "geography 地理, geology 地质", 3),
    ("aer/aero", "希腊", "空气", "air, aeroplane 飞机", 2),
    ("ign/ign", "拉丁", "火", "ignite 点燃, ignition 点火", 1),
    ("pyro/pyr", "希腊", "火", "pyrotechnics 烟花", 1),
    ("flamm/flagr", "拉丁", "火焰", "flammable 易燃, flagrant", 1),
    ("avi/avi", "拉丁", "鸟；飞行", "aviation 航空, aviator 飞行员", 1),
    ("ornith", "希腊", "鸟", "ornithology 鸟类学", 1),
    ("pisc/pisc", "拉丁", "鱼", "piscatorial 钓鱼的", 1),
    ("ichthy", "希腊", "鱼", "ichthyology 鱼类学", 1),
    ("equ/equ", "拉丁", "马", "equestrian 骑术的, equine 马的", 1),
    ("hipp/hippo", "希腊", "马", "hippopotamus 河马", 1),
    ("can/can", "拉丁", "狗", "canine 犬的, kennel 犬舍", 1),
    ("botan", "希腊", "植物", "botany 植物学, botanical", 1),
    ("phyt/phyte", "希腊", "植物", "phytoplankton 浮游植物", 1),
    ("arbor/arbor", "拉丁", "树", "arboretum 植物园", 1),
    ("dendr/dendron", "希腊", "树", "rhododendron 杜鹃花", 1),
    ("foli/foli", "拉丁", "叶子", "foliage 树叶, defoliate", 1),
    ("flor/flor", "拉丁", "花", "flower, floral 花的", 1),
    ("lign/ling", "拉丁", "木材", "lignite 褐煤", 1),
    ("herb/herb", "拉丁", "草", "herb 草药, herbivore 食草动物", 1),
    ("carn/carn", "拉丁", "肉", "carnivore 食肉动物, carnival", 2),
    ("omni/omni", "拉丁", "全部", "omnivore 杂食动物, omnipresent", 1),
    # ============ 身体 ============
    ("man/manu", "拉丁", "手", "manual 手册, manage 管理", 3),
    ("ped/pod", "拉丁/希腊", "脚", "pedal 踏板, pedestrian 行人", 3),
    ("corp/corpor", "拉丁", "身体", "corporate 公司, corpse 尸体", 2),
    ("anthrop/anthro", "希腊", "人", "anthropology 人类学", 2),
    ("card/cord/cardi", "拉丁/希腊", "心", "cardiac 心脏的, cordial", 2),
    ("dent/dont", "拉丁/希腊", "牙", "dentist 牙医, dental 牙齿的", 2),
    ("ocul/ocul", "拉丁", "眼", "ocular 眼睛的, binoculars", 1),
    ("capit/cap", "拉丁", "头", "capital 首都, captain 船长", 2),
    ("crani/cranio", "希腊", "头骨", "cranium 头颅, craniofacial", 1),
    ("faci/fac", "拉丁", "脸；面", "facial 面部的, surface 表面", 3),
    ("derm/dermat", "希腊", "皮肤", "dermatology 皮肤病学", 1),
    ("oste/osteo", "希腊", "骨", "osteoporosis 骨质疏松", 1),
    ("arthr/arthro", "希腊", "关节", "arthritis 关节炎", 1),
    ("musc/mus", "拉丁", "肌肉", "muscle 肌肉, muscular", 2),
    ("ven/veni", "拉丁", "血管", "vein 静脉, venous 静脉的", 1),
    ("sanguin", "拉丁", "血", "sanguine 乐观的, consanguinity", 1),
    ("hem/hemat", "希腊", "血", "hemoglobin 血红蛋白", 1),
    ("hepat/hepat", "希腊", "肝", "hepatitis 肝炎", 1),
    ("nephr/nephro", "希腊", "肾", "nephritis 肾炎", 1),
    ("cardi", "希腊", "心脏", "cardiology 心脏病学", 2),
    ("gastr/gastro", "希腊", "胃", "gastric 胃的, gastronomy", 1),
    ("enter/entero", "希腊", "肠", "enteritis 肠炎", 1),
    ("pneum/pulm", "希腊/拉丁", "肺", "pneumonia 肺炎, pulmonary", 1),
    ("rhin/rhino", "希腊", "鼻", "rhinoceros 犀牛, rhinitis", 1),
    ("ophthalm", "希腊", "眼", "ophthalmology 眼科学", 1),
    ("ot/oto", "希腊", "耳", "otitis 中耳炎, otolaryngology", 1),
    ("lingu/lingua", "拉丁", "舌头；语言", "language 语言, bilingual", 3),
    ("labi/lab", "拉丁", "唇", "labial 唇音的", 1),
    ("ungu/ungul", "拉丁", "爪；指甲", "ungulate 有蹄类", 1),
    # ============ 社会与秩序 ============
    ("dem/demo", "希腊", "民众", "democracy 民主, epidemic", 2),
    ("greg/greg", "拉丁", "群", "gregarious 爱交际, segregate", 2),
    ("jur/jus/jud", "拉丁", "法律；权利", "justice 正义, jury 陪审团", 3),
    ("leg/legis", "拉丁", "法律；读", "legal 合法, legislate 立法", 2),
    ("mand/mand", "拉丁", "命令", "command 命令, mandatory", 2),
    ("test/test", "拉丁", "见证", "testify 作证, contest 竞赛", 2),
    ("bell/belli", "拉丁", "战争", "rebel 反叛, belligerent 好战", 2),
    ("milit/milit", "拉丁", "士兵", "military 军队, militant 好斗", 2),
    ("neg/neg", "拉丁", "否认", "negative 否定, negotiate", 2),
    ("not/not", "拉丁", "标记", "note 笔记, notice 注意", 3),
    ("crim/crimin", "拉丁", "罪行", "crime 罪行, criminal 罪犯", 2),
    ("urb/urban", "拉丁", "城市", "urban 城市, suburb 郊区", 2),
    ("polit/polic", "希腊", "城市；政治", "politics 政治, police 警察", 2),
    ("civ/civil", "拉丁", "公民", "civil 公民的, city 城市", 3),
    ("popul/pop", "拉丁", "人民", "popular 受欢迎, population", 2),
    ("pac/pax", "拉丁", "和平", "pacific 和平的, pacify 平息", 1),
    ("serv/servi", "拉丁", "服务；奴", "service 服务, servant 仆人", 3),
    ("domin/dom", "拉丁", "主人；统治", "dominate 统治, domain 领域", 2),
    ("reg/rect/rex", "拉丁", "统治；直", "regular 规律, correct 纠正", 3),
    ("regal/royal", "拉丁/法语", "王室的", "regal 帝王的, royal 皇家的", 1),
    ("imper/empir", "拉丁", "统治", "empire 帝国, imperial 帝王的", 2),
    ("arch/arch", "希腊", "首领；统治", "monarch 君主, anarchy 无政府", 1),
    ("arist/arist", "希腊", "最好的", "aristocracy 贵族", 1),
    ("dem", "希腊", "人民", "democracy 民主", 2),
    ("tyrann", "希腊", "暴君", "tyrant 暴君, tyranny 暴政", 1),
    # ============ 属性与抽象 ============
    ("bene/bon/bon", "拉丁", "好", "benefit 好处, bonus 奖金", 3),
    ("mal/male", "拉丁", "坏", "malfunction 故障, malice 恶意", 2),
    ("pot/potent", "拉丁", "力量", "potential 潜力, omnipotent", 2),
    ("fort/fort", "拉丁", "强", "effort 努力, comfort 安慰", 3),
    ("val/vail/vali", "拉丁", "价值；强", "value 价值, valid 有效", 3),
    ("magn/maj/max", "拉丁", "大", "magnificent 壮丽, major 主要", 3),
    ("micro/micr", "希腊", "小", "microscope 显微镜, microbe", 2),
    ("mono/mon", "希腊", "一", "monopoly 垄断, monotonous", 2),
    ("un/uni", "拉丁", "一", "unique 唯一, union 联合", 3),
    ("nov/nov", "拉丁", "新", "novel 小说, innovate 创新", 3),
    ("ver/veri", "拉丁", "真", "verify 核实, verdict 裁决", 2),
    ("equ/equi", "拉丁", "相等", "equal 相等, equator 赤道", 3),
    ("liber/liber", "拉丁", "自由", "liberty 自由, liberate 解放", 2),
    ("vac/van/void", "拉丁", "空", "vacuum 真空, vanish 消失", 2),
    ("dynam/dynam", "希腊", "力量", "dynamic 动态, dynamite", 2),
    ("auto/aut", "希腊", "自己", "automatic 自动, autograph", 2),
    ("fin/finit", "拉丁", "结束；边界", "finish 完成, infinite 无限", 3),
    ("prim/prin", "拉丁", "第一", "primary 首要, prime 最佳", 3),
    ("clar/clar", "拉丁", "清晰", "clarify 澄清, declare", 2),
    ("vacu/vac", "拉丁", "空", "vacant 空缺, vacation 假期", 2),
    ("dens/dens", "拉丁", "密集", "dense 密集, density 密度", 2),
    ("dur/dur", "拉丁", "持久；坚硬", "during 期间, durable 耐用", 2),
    ("lev/lev", "拉丁", "轻；升起", "elevator 电梯, lever 杠杆", 2),
    ("medi/medi", "拉丁", "中间", "medium 媒介, median 中位数", 2),
    ("min/mini", "拉丁", "小；少", "minimum 最小, minority 少数", 2),
    ("par/par", "拉丁", "相等", "compare 比较, parallel 平行", 2),
    ("plen/plet", "拉丁", "满", "plenty 充足, complete 完整", 2),
    ("sol/soli", "拉丁", "单独", "sole 唯一, solitary 孤独", 1),
    ("simil/simul", "拉丁", "相似", "similar 相似, simulate 模拟", 2),
    ("vari/var", "拉丁", "变化；多样", "vary 变化, various 各种", 2),
    ("brevi/brev", "拉丁", "短", "brief 简短, abbreviate 缩写", 2),
    ("long/long", "拉丁", "长", "long 长, longitude 经度", 2),
    ("alt/alt", "拉丁", "高", "altitude 海拔, altimeter", 2),
    ("proxim/prox", "拉丁", "接近", "approximate 接近, proximity", 1),
    ("celer/celer", "拉丁", "快速", "accelerate 加速, celerity", 1),
    ("grav/grav", "拉丁", "重", "gravity 重力, grave 严重", 2),
    ("lumin/luc", "拉丁", "光", "illuminate, lucid", 2),
    ("radi/radix", "拉丁", "光线；根", "radio 无线电, radiation 辐射", 2),
    ("san/san", "拉丁", "健康", "sane 理智, sanitary 卫生", 1),
    ("salv/salv", "拉丁", "救", "salvation 拯救, salvage 打捞", 1),
    ("cura/cure", "拉丁", "照顾；治愈", "cure 治疗, secure 安全", 2),
    ("medic/med", "拉丁", "医药", "medical 医学, medicine 药", 2),
    ("pharmac/pharm", "希腊", "药", "pharmacy 药店, pharmacology", 1),
    ("tox/tox", "希腊/拉丁", "毒", "toxic 有毒, detox 排毒", 2),
    ("carcin/carcino", "希腊", "癌", "carcinoma 癌, carcinogen 致癌物", 1),
    ("germ/germ", "拉丁", "芽；细菌", "germ 细菌, germinate 发芽", 1),
    ("ven/ven", "拉丁", "静脉", "vein, venous", 1),
    # ============ 时间与度量 ============
    ("chron/chrono", "希腊", "时间", "chronic 慢性, synchronize 同步", 3),
    ("ann/enn/anni", "拉丁", "年", "annual 每年, anniversary", 2),
    ("numer/numer", "拉丁", "数字", "numerous 众多, enumerate", 2),
    ("meter/metr", "希腊", "测量", "thermometer 温度计, geometry", 2),
    ("tele/tel", "希腊", "远", "telephone 电话, telescope", 3),
    ("temp/tempor", "拉丁", "时间", "temporary 临时, contemporary", 2),
    ("hor/hor", "希腊", "小时；时辰", "hour 小时, horoscope 星座", 1),
    ("diur/diurnal", "拉丁", "白天", "diurnal 白天的, journal 日志", 1),
    ("noct/noct", "拉丁", "夜晚", "nocturnal 夜间的, nocturne", 1),
    ("aev/aev", "拉丁", "时代；年龄", "age 年龄, medieval 中世纪", 2),
    ("veter/veter", "拉丁", "老", "veteran 老兵, veterinary 兽医", 1),
    ("juven/juven", "拉丁", "年轻", "juvenile 青少年, rejuvenate 返老还童", 1),
    ("sen/sen", "拉丁", "老", "senior 年长, senate 参议院", 2),
    ("cent/cent", "拉丁", "百；百分", "century 世纪, percent 百分", 2),
    ("part/port", "拉丁", "部分", "part 部分, partition 分区", 3),
    ("tot/tot", "拉丁", "全部", "total 总数, totalitarian", 2),
    ("un/unit", "拉丁", "单位", "unit 单位, unity 团结", 3),
    ("bin/bin", "拉丁", "两个一组", "binary 二进制, combine 结合", 2),
    ("tern/tern", "拉丁", "三个一组", "ternary 三元", 1),
    ("quart/quart", "拉丁", "四分之一", "quarter 四分之一, quart 夸脱", 1),
    ("decim/decim", "拉丁", "十分之一", "decimal 十进制, decimate", 1),
    ("centen", "拉丁", "百年", "centennial 百年纪念", 1),
    ("millen/millenn", "拉丁", "千年", "millennium 千年", 1),
    # ============ 关系与连接 ============
    ("junct/join/join", "拉丁", "连接", "join 加入, junction 枢纽", 3),
    ("sequ/secut/suit", "拉丁", "跟随", "sequence 顺序, consequence", 3),
    ("duc/duct/duce", "拉丁", "引导", "educate 教育, produce 生产", 3),
    ("lect/leg/lig", "拉丁", "选；读", "collect 收集, select 选择", 3),
    ("plic/plex/ply", "拉丁", "折叠", "apply 申请, complex 复杂", 2),
    ("solv/solu/solut", "拉丁", "解开", "solve 解决, dissolve 溶解", 3),
    ("clud/clus/clos", "拉丁", "关闭", "include 包含, exclude 排除", 3),
    ("pend/pens/pend", "拉丁", "悬挂；称量", "depend 依靠, expensive 昂贵", 3),
    ("sed/sess/sid", "拉丁", "坐", "session 会议, resident 居民", 3),
    ("sta/stat/stit", "拉丁", "站", "state 状态, persist 坚持", 3),
    ("tend/tens/tent", "拉丁", "伸；拉", "attend 参加, extend 延伸", 3),
    ("trib/tribut", "拉丁", "给予", "contribute 贡献, distribute", 2),
    ("us/uti", "拉丁", "使用", "useful 有用, abuse 滥用", 3),
    ("here/hes", "拉丁", "粘着", "adhere 粘附, hesitate 犹豫", 1),
    ("liter/litera", "拉丁", "字母；文字", "literature 文学, literal 字面", 2),
    ("libr/libr", "拉丁", "书", "library 图书馆, librarian", 2),
    ("vert/vers/volv", "拉丁", "转", "convert 转变, reverse 反转", 3),
    ("vers/vert", "拉丁", "转", "version 版本, vertical 垂直", 3),
    ("rot/rot", "拉丁", "旋转", "rotate 旋转, rotary 旋转的", 1),
    ("gyr/gyro", "希腊", "旋转", "gyroscope 陀螺仪", 1),
    ("circ/circul", "拉丁", "圆；环绕", "circle 圆, circulate 循环", 2),
    ("glob/glob", "拉丁", "球", "global 全球, globe 地球", 2),
    ("orb/orbit", "拉丁", "圆；轨道", "orbit 轨道, orbital", 1),
    ("coron/coron", "拉丁", "王冠", "crown 王冠, corona 日冕", 1),
    ("termin/termin", "拉丁", "界限；末端", "terminal 终端, determine 决定", 2),
    ("limit/lim", "拉丁", "界限", "limit 限制, eliminate 排除", 2),
    ("extrem/extrem", "拉丁", "极端", "extreme 极端, extremity", 1),
    ("medi/medi", "拉丁", "中间", "median, medium", 2),
    ("centr/centr", "希腊", "中心", "center 中心, central 中心", 3),
    ("line/line", "拉丁", "线", "line 线, linear 线性", 2),
    ("rect/rect", "拉丁", "直", "correct 正确, rectangle 矩形", 3),
    ("curv/curv", "拉丁", "弯曲", "curve 曲线, curvature", 1),
    ("flect/flex", "拉丁", "弯", "reflect, flexible", 2),
    ("ambl", "希腊", "模糊", "ambiguous 含糊, ambition 野心", 1),
]
